### ISSUE TITLE
Donate Page - Please change "ZIP" to "Postal Code"

### ISSUE THREAD

**Issue by spalko** [CCI-Studios/legacyclub#4]

**Comment by ianfader** [comment]
Can Postal Code go on one line?

![screen shot 2017-02-13 at 4 48 56 pm](https://cloud.githubusercontent.com/assets/8989188/22904959/5d6526c6-f20c-11e6-86dc-cd471b18c108.png)

**Comment by ccmorris** [comment]
lol
